import type { Metadata } from "next";
import { ReactLenis } from "../libs/lenis";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LayoutWrapper from "@/components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Lafetch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactLenis root>
      <html lang="en">
        <body className={`relative`}>
          <Navbar />
          <LayoutWrapper>{children}</LayoutWrapper>
        </body>
      </html>
    </ReactLenis>
  );
}
